'use strict'
/*
  Open Rowing Monitor, https://github.com/laberning/openrowingmonitor

  This file contains the rower specific settings for different models of ergometers.

  These have been generated by the community. If your rower is not listed here and you did find
  good settings for your rowing device please send them to us (together with a raw recording of
  10 strokes) so we can add the device here.
*/
export default {

  // The default rower profile
  DEFAULT: {
    // How many impulses are triggered per revolution of the flywheel
    // i.e. the number of magnets if used with a reed sensor
    numOfImpulsesPerRevolution: 1,

    // NOISE FILTER SETTINGS
    // Filter Settings to reduce noise in the measured data
    // Minimum and maximum duration between impulses in seconds during active rowing. Measurements outside of this range
    // will be replaced by a default value.
    minimumTimeBetweenImpulses: 0.014,
    maximumTimeBetweenImpulses: 0.5,
    smoothing: 1,
    // Percentage change between successive intervals before measurements are considered invalid
    // smoothing determines the length of the running average for certain volatile measurements, 1 effectively turns it off
    maximumDownwardChange: 0.25, // effectively the maximum acceleration
    maximumUpwardChange: 1.75, // effectively the maximum decceleration
    smoothing: 1,

    // STROKE DETECTION SETTINGS
    // Flank length determines the minimum number of consecutive increasing/decreasing measuments are needed befor the stroke detection
    // considers a drive phase change
    // numberOfEroorsAllowed allows for a more noisy approach, but shouldn't be needed
    flankLength: 2,
    numberOfErrorsAllowed: 0,

    // Error reducing settings for the rowing phase detection (in seconds)
    maxCycleTimeBeforePause: 3.0,  // maximum time between impulses before the rowing engine considers it a pause
    minimumDriveTime: 0.300,       // minumum time of the drive phase
    minimumRecoveryTime: 1.200,    // minimumtime of the recovery phase

    // Needed to determine the drag factor of the rowing machine. This value can be measured in the recovery phase
    // of the stroke.
    // To display it for your rowing machine, set the logging level of the RowingEngine to 'info'. Then start rowing and
    // you will see the measured values in the log.
    // Just as a frame of reference: the Concept2 can display this factor from the menu, where it is multiplied with 1.000.000
    // For a new Concept2 the Drag Factor ranges between 0.000090 (Damper setting 1)  and 0.000220 (Damper setting 10)
    // Open Rowing Monitor can also automatically adjust this value based on the measured damping. To do so, set the setting
    // autoAdjustDampingConstant to true (see below).
    dragFactor: 0.000150,

    // The moment of inertia of the flywheel kg*m^2
    // A way to measure it is outlined here: https://dvernooy.github.io/projects/ergware/, "Flywheel moment of inertia"
    // You could also roughly estimate it by just doing some strokes and the comparing the calculated power values for
    // plausibility. Note that the power also depends on the drag factor (see above).
    flywheelInertia: 0.2036,

    // Set this to true, if you want to automatically update the drag factor based on the measured
    // values in the stroke recovery phase. If your rower produces stable damping values, then this could be a good
    // option to dynamically adjust your measurements to the damper setting of your rower.
    // When your machine's power and speed readings are too volatile it is wise to turn it off
    autoAdjustDampingConstant: true,

    // A constant that is commonly used to convert flywheel revolutions to a rowed distance
    // see here: http://eodg.atm.ox.ac.uk/user/dudhia/rowing/physics/ergometer.html#section9
    // Concept2 seems to use 2.8, which they admit is an arbitrary number which came close
    // to their expectations. So for your rower, you have to find a credible distance for your effort.
    // Also note that the rowed distance also depends on jMoment, so please calibrate that before changing this constant.
    // PLEASE NOTE: Increasing this number decreases your rowed meters
    magicConstant: 2.8,

  },

  // Sportstech WRX700
  WRX700: {
    numOfImpulsesPerRevolution: 2,
    flywheelInertia: 0.65,
    dragFactor: 0.000150
  },

  // DKN R-320 Air Rower
  DKNR320: {
    numOfImpulsesPerRevolution: 1,
    flywheelInertia: 0.41,
    dragFactor: 0.000150
  },

  // NordicTrack RX800 Air Rower
  RX800: {
    gpioHighPriority: true,
    numOfImpulsesPerRevolution: 4,

    /* Damper setting 10
    minimumTimeBetweenImpulses: 0.018,
    maximumTimeBetweenImpulses: 0.0338,
    maximumDownwardChange: 0.69,
    maximumUpwardChange: 1.3,
    flankLength: 3,
    numberOfErrorsAllowed: 0,
    minimumDriveTime: 0.300,
    minimumRecoveryTime: 0.750,
    omegaDotDivOmegaSquare: 0.00543660639574872,
    jMoment: 0.174, // still under investigation
    magicConstant: 3.75 // still under investigation
    */

    /* Damper setting 8
    minimumTimeBetweenImpulses: 0.017,
    maximumTimeBetweenImpulses: 0.034,
    maximumDownwardChange: 0.8,
    maximumUpwardChange: 1.15,
    minimumDriveTime: 0.300,
    minimumRecoveryTime: 0.750,
    omegaDotDivOmegaSquare: 0.005305471,
    jMoment: 0.155, // still under investigation
    magicConstant: 4 // still under investigation
    */

    /* Damper setting 6
    minimumTimeBetweenImpulses: 0.017,
    maximumTimeBetweenImpulses: 0.034,
    maximumDownwardChange: 0.85,
    maximumUpwardChange: 1.15,
    minimumDriveTime: 0.300,
    minimumRecoveryTime: 0.750,
    omegaDotDivOmegaSquare: 0.0047,
    jMoment: 0.135, // still under investigation
    magicConstant: 4.25 // still under investigation
    */

    /* Damper setting 4
    minimumTimeBetweenImpulses: 0.019,
    maximumTimeBetweenImpulses: 0.032,
    maximumDownwardChange: 0.70,
    maximumUpwardChange: 1.30,
    minimumDriveTime: 0.300,
    minimumRecoveryTime: 0.750,
    omegaDotDivOmegaSquare: 0.00355272,
    jMoment: 0.125, // still under investigation
    magicConstant: 4.4 // still under investigation
    */

    // Damper setting 2
    minimumTimeBetweenImpulses: 0.014,
    maximumTimeBetweenImpulses: 0.040,
    smoothing: 4,
    maximumDownwardChange: 0.962,
    maximumUpwardChange: 1.07,
    flankLength: 4,
    flywheelInertia: 0.2036,
    dragFactor: 0.0001318306
    //
  }
}
