'use strict'
/*
  Open Rowing Monitor, https://github.com/laberning/openrowingmonitor

  This file contains the rower specific settings for different models of ergometers.

  These have been generated by the community. If your rower is not listed here and you did find
  good settings for your rowing device please send them to us (together with a raw recording of
  10 strokes) so we can add the device here.
*/
export default {

  // Profile for an example rower
  DEFAULT: {
    // How many impulses are triggered per revolution of the flywheel
    // i.e. the number of magnets if used with a reed sensor
    numOfImpulsesPerRevolution: 1,

    // Needed to determine the damping constant of the rowing machine. This value can be measured in the recovery phase
    // of the stroke (some ergometers do this constantly).
    // However I still keep it constant here, as I still have to figure out the damping physics of a water rower (see below)
    // To measure it for your rowing machine, comment in the logging at the end of "startDrivePhase" function. Then do some
    // strokes on the rower and estimate a value.
    omegaDotDivOmegaSquare: 0.02,

    // The moment of inertia of the flywheel kg*m^2
    // A way to measure it is outlined here: https://dvernooy.github.io/projects/ergware/, "Flywheel moment of inertia"
    // You could also roughly estimate it by just doing some strokes and the comparing the calculated power values for
    // plausibility. Note that the power also depends on omegaDotDivOmegaSquare (see above).
    jMoment: 0.49,

    // Set this to true if you are using a water rower
    // The mass of the water starts rotating, when you pull the handle, and therefore acts
    // like a massive flywheel
    // Liquids are a tricky thing and therefore the dumping constant does not seem to be
    // that constant on water rowers...
    // This is WIP, but for now this setting is used to figure out the drive and recovery phases
    // differently on water rowers
    liquidFlywheel: false
  },

  // Sportstech WRX700
  WRX700: {
    numOfImpulsesPerRevolution: 2,
    omegaDotDivOmegaSquare: 0.046,
    jMoment: 0.49,
    liquidFlywheel: true
  },

  // DKN R-320 Air Rower
  DKNR320: {
    numOfImpulsesPerRevolution: 1,
    omegaDotDivOmegaSquare: 0.019,
    jMoment: 0.4,
    liquidFlywheel: true
  }
}
