'use strict'
/**
 * @copyright [OpenRowingMonitor]{@link https://github.com/JaapvanEkris/openrowingmonitor}
 *
 * @file This file contains the rower specific settings for different models of ergometers.
 *
 * These have been generated by the community. If your rower is not listed here, please follow
 * https://github.com/JaapvanEkris/openrowingmonitor/blob/main/docs/rower_settings.md to find the right settings
 * After you found good settings for your rowing device please send them to us (together with a raw recording
 * of at least 10 strokes) so we can add the device here and start to maintain it.
 */

/* eslint-disable camelcase -- Machine names are much easier to read like this */
export default {

  // The default rower profile
  DEFAULT: {
    // How many impulses are triggered per revolution of the flywheel
    // i.e. the number of magnets if used with a reed sensor
    numOfImpulsesPerRevolution: 1,

    // How big the sprocket is that attaches your belt/chain to your flywheel. This determines both the force on the handle
    // as well as the drive length. If all goes well, you end up with average forces around 300 to 800 N and drive lengths around 1.20 to 1.45 m
    sprocketRadius: 7.0,

    // Minimum and maximum duration between impulses in seconds during active rowing. Measurements above the maximum are filtered, so setting these liberaly
    // might help here
    minimumTimeBetweenImpulses: 0.014,
    maximumTimeBetweenImpulses: 0.5,

    // NOISE FILTER SETTINGS
    // Filter Settings to reduce noise in the measured data
    // Systematic error agressiveness determines the strength of the systematic error filter. 0 turns it off (default), 1 turns it to its maximum.
    // A value of 0.10 is known to bring some benefits, but some machines can handle 0.90 to 1.0. Don't set too high if the machine has a lot of signal bounce.
    systematicErrorAgressiveness: 0,

    // Size of the total buffer for the systematic error filter. We recomend to use at least use the length of the longest recovery here (logs can tell this).
    systematicErrorNumberOfDatapoints: 1,

    // Flank length determines the number of measuments that are used for determining the angular velocity and angular acceleration
    flankLength: 3,

    // STROKE DETECTION SETTINGS
    // This is the minimum force that has to be on the handle before ORM considers it a stroke, in Newtons. So this is about 2 Kg or 4.4 Lbs.
    minimumForceBeforeStroke: 20,

    // The minimal inclination of the currentDt's before it is considered a recovery. When set to 0, it will look for a pure increase/decrease
    minimumRecoverySlope: 0,

    // The minimum quality level of the stroke detection: 1.0 is perfect, 0.1 pretty bad. Normally around 0.33. Setting this too high will stop
    // the recovery phase from being detected through the slope angle (i.e. it will completely rely on the absence of the minimumForceBeforeStroke).
    minimumStrokeQuality: 0.34,

    // ORM can automatically calculate the recovery slope and adjust it dynamically. For this to work, autoAdjustDragFactor MUST be set to true
    autoAdjustRecoverySlope: false,

    // The margin used between the automatically calculated recovery slope and a next recovery. Don't touch unless you know what you are doing.
    autoAdjustRecoverySlopeMargin: 0.05,

    // Error reducing settings for the rowing phase detection (in seconds)
    minimumDriveTime: 0.300, // minimum time of the drive phase
    minimumRecoveryTime: 0.900, // minimum time of the recovery phase

    // Needed to determine the drag factor of the rowing machine. This value can be measured in the recovery phasse of the stroke.
    // To display it for your rowing machine, set the logging level of the RowingEngine to 'info'. Then start rowing and you will see the measured
    // values in the log.
    // Just as a frame of reference: the Concept2 can display this factor from the menu, where it ranges between 80 (Damper setting 1) to 220 (Damper setting 10).
    // Other rowers are in the range of 150 to 450 (NordicTrack), but more extreme values are found in waterrowers (for example 32000)
    // Open Rowing Monitor can also automatically adjust this value based on the measured damping. To do so, set the setting
    // autoAdjustDragFactor to true (see below) and set the flywheel inertia.
    dragFactor: 1500,

    // Set this to true, if you want to automatically update the drag factor based on the measured
    // values in the stroke recovery phase. If your rower produces stable damping values, then this could be a good
    // option to dynamically adjust your measurements to the damper setting of your rower.
    // When your machine's power and speed readings are too volatile it is wise to turn it off
    autoAdjustDragFactor: false,

    // If autoAdjustDragFactor is set to true, it will calculate the drag each recovery phase and update it accordingly to calculate speed,
    // distance, etc.. As this calculation that is prone to noise in the measuremnts, it is wise to apply smoothing to prevent this noise
    // from throwing off your key metrics. The default value is a running average of the drag factor of 5 strokes
    dragFactorSmoothing: 5,

    // When drag is calculated, we also get a quality indication. Based on this quality indication (1.0 is best, 0.1 pretty bad), low quality
    // drag factors are rejected to prevent drag poisoning
    minimumDragQuality: 0.83,

    // The moment of inertia of the flywheel kg*m^2
    // A way to measure it is outlined here: https://dvernooy.github.io/projects/ergware/, "Flywheel moment of inertia"
    // You could also roughly estimate it by just doing some strokes and the comparing the calculated power values for
    // plausibility. Note that the power also depends on the drag factor (see above).
    flywheelInertia: 0.5,

    // The time before a stroke is considered paused
    maximumStrokeTimeBeforePause: 6.0,

    // A constant that is commonly used to convert flywheel revolutions to a rowed distance
    // see here: http://eodg.atm.ox.ac.uk/user/dudhia/rowing/physics/ergometer.html#section9
    // Concept2 seems to use 2.8, which they admit is an arbitrary number which came close
    // to their expectations. So for your rower, you have to find a plausible distance for your effort.
    // Also note that the rowed distance also depends on flywheelInertia, so please calibrate that before changing this constant.
    // PLEASE NOTE: Increasing this number decreases your rowed meters
    magicConstant: 2.8
  },

  // Cheap Clone of Concept2 RowErg Model D
  // https://zocobodyfit.ro/produs/aparat-de-vaslit-zoco-body-fit-air-rower-pliabil-ecran-lcd-eficient-si-util-negru/
  Generic_Air_Rower: {
    numOfImpulsesPerRevolution: 1,
    minimumTimeBetweenImpulses: 0.007,
    sprocketRadius: 1.55,
    flankLength: 6,
    minimumForceBeforeStroke: 2,
    minimumStrokeQuality: 0.6,
    minimumDriveTime: 0.200,
    minimumRecoveryTime: 0.600,
    dragFactor: 108,
    autoAdjustDragFactor: true,
    dragFactorSmoothing: 1,
    minimumDragQuality: 0.97,
    flywheelInertia: 0.073,
    maximumStrokeTimeBeforePause: 6.0
  },

  // Concept2 RowErg, Model B and C
  Concept2_Model_C: {
    numOfImpulsesPerRevolution: 3,
    minimumTimeBetweenImpulses: 0.014,
    maximumTimeBetweenImpulses: 0.040,
    sprocketRadius: 1.4,
    flankLength: 6,
    systematicErrorAgressiveness: 0.975,
    systematicErrorNumberOfDatapoints: 260,
    minimumForceBeforeStroke: 50,
    minimumRecoverySlope: 0.00070,
    minimumStrokeQuality: 0.36,
    autoAdjustRecoverySlope: true,
    autoAdjustRecoverySlopeMargin: 0.01,
    minimumDriveTime: 0.400,
    minimumRecoveryTime: 0.900,
    dragFactor: 110,
    autoAdjustDragFactor: true,
    dragFactorSmoothing: 3,
    minimumDragQuality: 0.95,
    flywheelInertia: 0.10148,
    maximumStrokeTimeBeforePause: 6.0,
    magicConstant: 2.8
  },

  // Concept2 RowErg, Model D, E and RowErg
  Concept2_RowErg: {
    numOfImpulsesPerRevolution: 6,
    minimumTimeBetweenImpulses: 0.005,
    maximumTimeBetweenImpulses: 0.013125,
    sprocketRadius: 1.4,
    flankLength: 12,
    systematicErrorAgressiveness: 0.975,
    systematicErrorNumberOfDatapoints: 520,
    maximumStrokeTimeBeforePause: 6.0,
    dragFactor: 68,
    autoAdjustDragFactor: true,
    minimumDragQuality: 0.85,
    dragFactorSmoothing: 3,
    minimumStrokeQuality: 0.26,
    minimumForceBeforeStroke: 22,
    minimumRecoverySlope: 0.00070,
    autoAdjustRecoverySlope: true,
    autoAdjustRecoverySlopeMargin: 0.0045,
    minimumDriveTime: 0.50,
    minimumRecoveryTime: 0.90,
    flywheelInertia: 0.101545,
    magicConstant: 2.8
  },

  // DKN R-320 Air Rower
  DKN_R320: {
    numOfImpulsesPerRevolution: 1,
    flywheelInertia: 0.94,
    dragFactor: 8522
  },

  // Force USA R3 Air Rower, see https://github.com/JaapvanEkris/openrowingmonitor/discussions/185
  ForceUSA_R3: {
    numOfImpulsesPerRevolution: 6,
    minimumTimeBetweenImpulses: 0.005,
    maximumTimeBetweenImpulses: 0.022,
    flywheelInertia: 0.1015,
    flankLength: 10,
    dragFactor: 135,
    autoAdjustDragFactor: true,
    // new engine settings
    sprocketRadius: 1.5,
    minimumStrokeQuality: 0.50,
    minimumRecoverySlope: 0.00070,
    autoAdjustRecoverySlope: true,
    autoAdjustRecoverySlopeMargin: 0.035,
    minimumForceBeforeStroke: 20,
    minimumDriveTime: 0.46,
    minimumRecoveryTime: 0.80,
    minimumDragQuality: 0.83,
    dragFactorSmoothing: 3,
    maximumStrokeTimeBeforePause: 4
  },

  // KayakFirst kayak/canoe erg (2020 model blue, non-bull)
  KayakFirst_Blue: {
    numOfImpulsesPerRevolution: 6,
    minimumTimeBetweenImpulses: 0.005,
    maximumTimeBetweenImpulses: 0.0145,
    sprocketRadius: 2.7,
    maximumStrokeTimeBeforePause: 7.0,
    dragFactor: 40,
    autoAdjustDragFactor: true,
    minimumDragQuality: 0.736,
    dragFactorSmoothing: 4,
    flankLength: 12,
    minimumForceBeforeStroke: 1,
    minimumDriveTime: 0.145,
    minimumRecoveryTime: 0.17,
    flywheelInertia: 0.039,
    magicConstant: 3.45
  },

  Merach_R50: {
    numOfImpulsesPerRevolution: 1,
    minimumTimeBetweenImpulses: 0.03,
    maximumTimeBetweenImpulses: 0.08,
    sprocketRadius: 1.43,
    flankLength: 4,
    systematicErrorAgressiveness: 0,
    systematicErrorNumberOfDatapoints: 0,
    minimumStrokeQuality: 0.3,
    minimumRecoverySlope: 0.0,
    autoAdjustRecoverySlope: true,
    autoAdjustRecoverySlopeMargin: 0.05,
    minimumForceBeforeStroke: 25,
    flywheelInertia: 0.105,
    dragFactor: 107,
    autoAdjustDragFactor: true,
    minimumDragQuality: 0.85,
    dragFactorSmoothing: 3,
    minimumDriveTime: 0.50,
    minimumRecoveryTime: 0.90,
    maximumStrokeTimeBeforePause: 6.0,
    magicConstant: 2.8
  },

  // NordicTrack RX800 Air Rower
  NordicTrack_RX800: {
    numOfImpulsesPerRevolution: 4,
    minimumTimeBetweenImpulses: 0.005,
    maximumTimeBetweenImpulses: 0.045,
    sprocketRadius: 3.0,
    autoAdjustDragFactor: true,
    minimumDragQuality: 0.83,
    dragFactorSmoothing: 3,
    flywheelInertia: 0.180,
    dragFactor: 225,
    flankLength: 7,
    minimumStrokeQuality: 0.34,
    minimumRecoverySlope: 0,
    autoAdjustRecoverySlope: true,
    autoAdjustRecoverySlopeMargin: 0.14,
    minimumForceBeforeStroke: 35,
    minimumDriveTime: 0.30,
    minimumRecoveryTime: 0.60
  },

  // Oartec slider, see https://github.com/JaapvanEkris/openrowingmonitor/discussions/218
  Oartec_Slider: {
    numOfImpulsesPerRevolution: 3,
    sprocketRadius: 1.4148,
    minimumTimeBetweenImpulses: 0.01,
    maximumTimeBetweenImpulses: 0.06,
    flankLength: 6,
    systematicErrorAgressiveness: 0.975,
    systematicErrorNumberOfDatapoints: 220,
    minimumForceBeforeStroke: 10,
    minimumRecoverySlope: 0,
    minimumStrokeQuality: 0.33,
    autoAdjustRecoverySlope: true,
    autoAdjustRecoverySlopeMargin: 0.05,
    minimumDriveTime: 0.300,
    minimumRecoveryTime: 0.900,
    dragFactor: 150,
    autoAdjustDragFactor: true,
    dragFactorSmoothing: 3,
    minimumDragQuality: 0.9,
    flywheelInertia: 0.1057,
    maximumStrokeTimeBeforePause: 6.0,
    magicConstant: 2.8
  },

  // Schwinn Windrigger, see https://github.com/JaapvanEkris/openrowingmonitor/discussions/159
  Schwinn_Windrigger: {
    numOfImpulsesPerRevolution: 1,
    minimumTimeBetweenImpulses: 0.03,
    maximumTimeBetweenImpulses: 0.3,
    sprocketRadius: 1.57,
    flankLength: 3,
    minimumForceBeforeStroke: 30,
    minimumStrokeQuality: 0.20,
    minimumRecoverySlope: 0.0,
    autoAdjustRecoverySlope: true,
    autoAdjustRecoverySlopeMargin: 0.1,
    dragFactor: 100,
    autoAdjustDragFactor: true,
    dragFactorSmoothing: 3,
    minimumDragQuality: 0.85,
    minimumDriveTime: 0.300,
    minimumRecoveryTime: 0.900,
    flywheelInertia: 0.08,
    maximumStrokeTimeBeforePause: 6.0,
    magicConstant: 2.8
  },

  // Sportstech WRX700
  Sportstech_WRX700: {
    numOfImpulsesPerRevolution: 2,
    minimumTimeBetweenImpulses: 0.005,
    maximumTimeBetweenImpulses: 0.5,
    minimumRecoverySlope: 0,
    flywheelInertia: 0.72,
    dragFactor: 32000
  },

  // TESTING PURPOSES ONLY!! DO NOT USE FOR PRODUCTION MACHINES!!
  // Theoretical model used for validation testing with the theoretical simulations in the recordings
  // see https://github.com/JaapvanEkris/openrowingmonitor/discussions/215
  Theoretical_Model: {
    numOfImpulsesPerRevolution: 6,
    minimumTimeBetweenImpulses: 0.005,
    maximumTimeBetweenImpulses: 0.01375,
    sprocketRadius: 1.415,
    dragFactor: 68,
    autoAdjustDragFactor: true,
    minimumDragQuality: 0.85,
    dragFactorSmoothing: 3,
    flankLength: 12,
    systematicErrorAgressiveness: 1,
    systematicErrorNumberOfDatapoints: 520,
    minimumStrokeQuality: 0.34,
    minimumForceBeforeStroke: 17.5,
    minimumRecoverySlope: 0.00070,
    autoAdjustRecoverySlope: true,
    autoAdjustRecoverySlopeMargin: 0.0045,
    minimumDriveTime: 0.50,
    minimumRecoveryTime: 0.90,
    maximumStrokeTimeBeforePause: 6.0,
    flywheelInertia: 0.1001,
    magicConstant: 2.8
  },

  // Topiom V2 Water Rower, https://github.com/JaapvanEkris/openrowingmonitor/discussions/144
  Topiom_V2: {
    numOfImpulsesPerRevolution: 1,
    minimumTimeBetweenImpulses: 0.2,
    maximumTimeBetweenImpulses: 0.6,
    SprocketRadius: 5,
    minimumForceBeforeStroke: 80,
    minimumRecoverySlope: 0,
    minimumRecoveryTime: 0.3,
    dragFactor: 23000,
    flywheelInertia: 0.8
  },

  // Virtufit Magnetic Rowing Machine
  // https://virtufit.nl/wp-content/uploads/2022/01/VirtuFit-Elite-Magnetic-Rowing-Machine-Manual-EN.pdf
  // aka: Obelix - https://pesaschile.cl/categorias/1162-remo-de-aire-magnetico-lite-series-obelix.html
  // https://fedesport.cl/products/remo-de-aire-magnetico-lite-series-obelix
  virtufit: {
    numOfImpulsesPerRevolution: 4,
    minimumTimeBetweenImpulses: 0.007,
    dragFactor: 380,
    autoAdjustDragFactor: true,
    minimumDragQuality: 0.93,
    autoAdjustRecoverySlope: true,
    autoAdjustRecoverySlopeMargin: 0.5,
    minimumForceBeforeStroke: 10,
    flankLength: 4,
    minimumDriveTime: 0.30,
    minimumRecoveryTime: 0.020,
    flywheelInertia: 0.015,
    maximumStrokeTimeBeforePause: 10.0
  }
}
